[Step1] 재근, 에라
tasty-code/ios-open-market pull request #1
Opened 2022-10-26 03:12 UTC by wormsJJG

@jaemuYeo  리뷰 부탁드립니다!

## 구현 목록
☑ JSON 데이터 매핑할 모델 설계
☑ URL Session을 활용한 서버와의 통신
☑ CodingKeys 홯용
☑ 가짜 데이터와 네트워크 통신 단위 테스트

## 타입 설계 (JSON 매핑할 타입)
<img width="582" alt="스크린샷 2022-10-26 오후 12 03 45" src="https://user-images.githubusercontent.com/81068345/197924767-acf69921-1efa-468d-b536-17d85dee8b83.png">

<img width="520" alt="스크린샷 2022-10-26 오후 12 03 57" src="https://user-images.githubusercontent.com/81068345/197924785-54c20399-49a4-44a4-90fa-28abff725d41.png">

☑ 변수명은 Swift 컨벤션에 맞춰 스네이크 코드를 사용하지 않고 CodingKey를 활용하였습니다.
☑ 통신결과 데이터에 없을 수도 있는 데이터는 옵셔널로 처리하였습니다.

## 네트워크 통신 
<img width="1671" alt="스크린샷 2022-10-26 오후 12 05 19" src="https://user-images.githubusercontent.com/81068345/197924962-ed8bd5ee-4070-455f-a640-a51d6bc7da9a.png">

☑ Request 열거형을 따로 만들어 입력해야할 request값과 URL을 관리하였습니다.

<img width="810" alt="스크린샷 2022-10-26 오후 12 06 31" src="https://user-images.githubusercontent.com/81068345/197925119-49b65534-54d6-431a-af69-d81645fdda3f.png">

☑  네트워크 통신 과정에서 생길 수 있는 에러를 NetworkError를 통해 관리합니다.

<img width="690" alt="스크린샷 2022-10-26 오후 12 07 07" src="https://user-images.githubusercontent.com/81068345/197925177-6913eae0-d89f-4465-bcdb-d5d0343656ed.png">

☑  HTTP 메서드, 상태코드를 따로 타입으로 만들어 매직넘버를 없앴습니다.

<img width="2130" alt="스크린샷 2022-10-26 오후 12 07 47" src="https://user-images.githubusercontent.com/81068345/197925242-42e0867a-444c-4e44-ae60-5933b07d121c.png">

☑  HTTP Request CompletionHandler는 비동기로 실행 되기 떄문에 @escaping을 사용하였습니다.

## 단위테스트
<img width="1868" alt="스크린샷 2022-10-26 오후 12 11 09" src="https://user-images.githubusercontent.com/81068345/197925676-d4c9f477-465e-430d-8999-56476e1f8e06.png">

Mock데이터를 불러와 제대로 디코딩을 하는지 ☑ 
API로 데이터를 가져와 디코딩을 잘 수행하였는지 ☑

2022-10-26 12:21 UTC, jaemuYeo requested changes
재근 에라 스텝1 고생많았습니다!!
마지막 프로젝트이니만큼 코멘트를 남기는 것도 더 신중해지는 것 같네요 ㅎㅎ
끝까지 응원하겠습니다 💪

클론 받은 프로젝트에서 프로토콜 폴더를 확인했어요!
<img width="272" alt="스크린샷 2022-10-26 오후 7 57 54" src="https://user-images.githubusercontent.com/70311145/198009893-671dc5a6-9516-4d5c-8baa-030a5e63f52a.png">
프로토콜을 구현하려다 지우신건가요? 저 빨간색은 무엇을 뜻할까요 ㅎㅎ
POP도 적극활용해보았음 좋겠습니다! 🙂

`Rresult 타입`에 대해서도 적용한 점 멋져요 💯

그 외 코멘트는 코드에 남겨놓겠습니다~~

2022-10-26 12:21 UTC, jaemuYeo commented on OpenMarket/OpenMarket/Model/Network/HTTP.swift
> +enum HTTPMethod: String {
지금처럼 구현하게되면 rawValue를 통해 접근할텐데 더 좋은 방법은 없을까요?
저라면 이럴때 static let을 활용할 것같아요!
이전 프로젝트에서 static let 난발해놓고 왜 이번에는 마다한거죠?? ㅎㅎㅎㅎ

2022-10-26 12:21 UTC, jaemuYeo commented on OpenMarket/OpenMarket/Model/Network/HTTP.swift
> +    case GET = "GET"
케이스는 소문자카멜케이스로 구현한답니다 :)

2022-10-26 12:21 UTC, jaemuYeo commented on OpenMarket/OpenMarket/Model/Network/HTTP.swift
> +    case continueStatus
여기는 소문자로 했네요?! ^^

2022-10-26 12:21 UTC, jaemuYeo commented on OpenMarket/OpenMarket/Model/Network/NetworkError.swift
> +enum NetworkError: Error, LocalizedError {
LocalizedError 활용 좋습니다

2022-10-26 12:21 UTC, jaemuYeo commented on OpenMarket/OpenMarket/Model/Network/NetworkManager.swift
> +class NetworkManager {
네이밍 좋네요 👍

2022-10-26 12:21 UTC, jaemuYeo commented on OpenMarket/OpenMarket/Model/Network/NetworkManager.swift
> +    init() {
urlSession 프로퍼티에 바로 기본값으로 주지않고 init을 통해 기본값을 준 이유가 있나요??
해당 프로퍼티는 dataTask메서드에서만 사용되고 있는데 메서드 내부에서 선언하지 않은 이유는 무엇인가요?

2022-10-26 12:21 UTC, jaemuYeo commented on OpenMarket/OpenMarket/Model/Network/NetworkManager.swift
> +    func dataTask(request: URLRequest, completionHandler: @escaping(Result<Data, NetworkError>) -> Void ) {
completionHandler -> completion으로 축약해도 좋을 것 같습니다!

해당 메서드에서 error에 대한 부분은 왜 처리해주지 않았나요??

2022-10-26 12:21 UTC, jaemuYeo commented on OpenMarket/OpenMarket/Model/Network/NetworkManager.swift
> +            }
guard let 사이에 한번 개행해서 가독성올려주세요~

2022-10-26 12:21 UTC, jaemuYeo commented on OpenMarket/OpenMarket/Model/Network/NetworkManager.swift
> +    func getData(requestType: Request, completionHandler: @escaping(Result<Data, NetworkError>) -> Void ) {
여기도 completionHandler을 축약하면 좋을 것 같아요~

2022-10-26 12:21 UTC, jaemuYeo commented on OpenMarket/OpenMarket/Model/Network/Request.swift
> +    static let apiHost = "https://openmarket.yagom-academy.kr"
저는 host주소, URI, URL, Query 등은 따로 타입을 만들어서 보관하는 편입니다 😉

2022-10-26 12:21 UTC, jaemuYeo commented on OpenMarket/OpenMarket/Model/Type/Currency.swift
> +    case USD
케이스는 소문자 카멜케이스로 해주세요!
```swift
enum Currency: String, Codable {
    case usd = "USD"
    case krw = "KRW"
}
```

2022-10-26 12:21 UTC, jaemuYeo commented on OpenMarket/OpenMarket/Model/Type/Image.swift
> +struct Image: Codable {
모든 모델 타입에 Decodable이 아닌 Codable을 채택한 이유가 있나요??

2022-10-26 12:21 UTC, jaemuYeo commented on OpenMarket/OpenMarket/Model/Type/Product.swift
> +    let vendorName: String?
옵셔널이 있는 부분들은 null이라는 값이 있는 것을 확인했나요?!
옵셔널 타입으로 선언한 이유가 무엇인가요??

2022-10-26 12:21 UTC, jaemuYeo commented on OpenMarket/OpenMarket/Model/Type/Product.swift
> +    let images: [Image]?
images와 vendors는 product에 해당하는 부분인가요?

2022-10-26 12:21 UTC, jaemuYeo commented on OpenMarket/OpenMarket/Model/Type/ProductListPage.swift
> +    let productList: [Product]
JSON 키값과 웬만하면 네이밍을 맞춰주세요 :)
pages 군요!

2022-10-27 00:38 UTC, wormsJJG commented on OpenMarket/OpenMarket/Model/Network/HTTP.swift
> +enum HTTPMethod: String {
아직 static let을 이해하는데 좀 시간이 걸린 것 같습니다 어제 이후로 static let을 확실히 이해하여 이제는 잘 쓰겠습니다 ㅎㅎㅎㅎㅎㅎ

2022-10-27 00:39 UTC, wormsJJG commented on OpenMarket/OpenMarket/Model/Network/HTTP.swift
> +    case GET = "GET"
넵!

2022-10-27 00:39 UTC, wormsJJG commented on OpenMarket/OpenMarket/Model/Network/HTTP.swift
> +    case continueStatus
핫...

2022-10-27 00:39 UTC, wormsJJG commented on OpenMarket/OpenMarket/Model/Network/NetworkError.swift
> +enum NetworkError: Error, LocalizedError {
ㅎㅎ

2022-10-27 00:39 UTC, wormsJJG commented on OpenMarket/OpenMarket/Model/Network/NetworkManager.swift
> +class NetworkManager {
하하 잼킹한테 네이밍으로 칭찬을 받다니 이보다 값진 칭찬은 없습니다

2022-10-27 00:40 UTC, kr-yeon commented on OpenMarket/OpenMarket/Model/Type/ProductListPage.swift
> +    let productList: [Product]
포스트맨기준 API의 이름은 상품 리스트 조회였습니다.
pages의 value는 상품이 배열의 형태로 들어가 있다고 생각되어 저러한 네이밍을 채택했습니다.
pages로 할 경우, page의 집합같은 느낌이 들어 저러한 백엔드의 네이밍을 수정해주었습니다.

2022-10-27 00:40 UTC, wormsJJG commented on OpenMarket/OpenMarket/Model/Network/NetworkManager.swift
> +            }
넵

2022-10-27 00:43 UTC, wormsJJG commented on OpenMarket/OpenMarket/Model/Network/NetworkManager.swift
> +    func dataTask(request: URLRequest, completionHandler: @escaping(Result<Data, NetworkError>) -> Void ) {
해당 메서드에서는 상태코드 에러, 데이터파일 불러오기 실패로 에러를 처리하고있습니다

2022-10-27 00:43 UTC, kr-yeon commented on OpenMarket/OpenMarket/Model/Type/Product.swift
> +    let images: [Image]?
상품 상세 조회 API와 삼품 목록의 pages내부 원소의 형태가 비슷하여 하나의 타입으로 정의하고, 다른 부분을 옵셔널로 처리하였습니다.
해당 images와 vendors는 상품 상세 조회 api의 key값 입니다.
비슷한 원소가 많아 코드의 중복을 줄이는 목적으로 저러한 형태를 채택하였습니다.

2022-10-27 00:44 UTC, kr-yeon commented on OpenMarket/OpenMarket/Model/Type/Product.swift
> +    let vendorName: String?
* 상품 상세 조회 API와 삼품 목록의 pages내부 원소의 형태가 비슷하여 하나의 타입으로 정의하고, 다른 부분을 옵셔널로 처리하였습니다.
해당 vendorName은 상품 상세 조회 api에서 존재하지 않는 값입니다.

2022-10-27 00:45 UTC, wormsJJG commented on OpenMarket/OpenMarket/Model/Network/NetworkManager.swift
> +    init() {
dataTask 메서드안에 URLSession에 대한 선언 구문이 들어가게 되면 가독성이 안좋아진다고 생각합니다. 그래서 urlSession을 선언 후 init이 될때 기본값을 주었습니다.

2022-10-27 00:47 UTC, kr-yeon commented on OpenMarket/OpenMarket/Model/Type/Image.swift
> +struct Image: Codable {
API호출단에서 다름을 실수로 인지하지 못했네요..!
수정하겠습니다!

2022-10-27 00:48 UTC, kr-yeon commented on OpenMarket/OpenMarket/Model/Type/Currency.swift
> +    case USD
각 네이밍이 이미 약자임을 인식하지 않았네요.
수정하겠습니다!

2022-10-27 00:54 UTC, kr-yeon commented on OpenMarket/OpenMarket/Model/Network/Request.swift
> +    static let apiHost = "https://openmarket.yagom-academy.kr"
넵

2022-10-27 00:55 UTC, kr-yeon commented on OpenMarket/OpenMarket/Model/Network/NetworkManager.swift
> +    func getData(requestType: Request, completionHandler: @escaping(Result<Data, NetworkError>) -> Void ) {
넵

2022-10-27 00:55 UTC, kr-yeon commented on OpenMarket/OpenMarket/Model/Network/NetworkManager.swift
> +            }
넵

2022-10-28 07:25 UTC, jaemuYeo requested changes
재근 에라 리뷰 반영하느라 고생하셨습니다!
다만 조금 아쉬운 부분들이 남아 한 번 더 요청드려요~
궁금한 점은 언제든 말씀해주세요!!

2022-10-28 07:25 UTC, jaemuYeo commented on OpenMarket/OpenMarket/Model/Network/NetworkError.swift
> +    case HTTPStatusCodeError
이 곳의 케이스들도 대문자로 시작하고 있네요!
수정해볼까요??

2022-10-28 07:25 UTC, jaemuYeo commented on OpenMarket/OpenMarket/Model/Network/NetworkError.swift
> +    case UnownURL
unknown 을 잘못 넣어놓은 건가요??
unknown은 자체로 에러를 나두는 것이 좋을 것같아요!
invalidURL같은 네이밍은 어떤가요?

2022-10-28 07:25 UTC, jaemuYeo commented on OpenMarket/OpenMarket/Model/Network/NetworkManager.swift
> +class NetworkManager {
[이 문서](https://github.com/apple/swift/blob/main/docs/OptimizationTips.rst#advice-use-final-when-you-know-the-declaration-does-not-need-to-be-overridden)를 보면 final class에 대한 이점에 대해 설명해주고 있어요~
상속과 오버라이딩이 필요하지 않은 경우는 해당 객체를 포함해 final를 붙여보는 건 어떤가요?

2022-10-28 07:25 UTC, jaemuYeo commented on OpenMarket/OpenMarket/Model/Network/NetworkManager.swift
> +            }
complition과 중괄호 사이에 개행한번 해주면 가독성이 좋아요!

2022-10-28 07:25 UTC, jaemuYeo commented on OpenMarket/OpenMarket/Model/Network/NetworkManager.swift
> +        }
중괄호와 resume 사이에 개행이 있으면 가독성이 좋을 것 같습니다!

2022-10-28 07:25 UTC, jaemuYeo commented on OpenMarket/OpenMarket/Model/Network/Request.swift
> +    case getProductList(pageNo: Int, itemsPerPage: Int)
케이스의 네이밍이 함수같네요 🤔

2022-10-28 07:25 UTC, jaemuYeo commented on OpenMarket/OpenMarket/Model/Network/Request.swift
> +    var url: String {
url을 문자를 바로 입력하지 않고 조금 더 코드화 시켜서 담아보는 방식은 어떤가요?
너무 간략하게 하는 것도 가끔은 독이 된답니다~
URL의 헤더 바디 쿼리파라미터 등을 조합해서 return할 수 있도록 수정해보았으면 좋곘어요!

2022-10-28 07:25 UTC, jaemuYeo commented on OpenMarket/OpenMarket/Model/Type/Product.swift
> +struct Product: Codable {
해당 형식은 [문서](https://developer.apple.com/documentation/foundation/jsondecoder/keydecodingstrategy/convertfromsnakecase)에 나오는 것과 비슷한 형태로 보이는군요!!
애플에서 제공하는 디코딩 전략입니다~ 꼭 적용해보지는 않아도 좋지만
참고해보면 좋을 것 같아 공유해요!!

2022-10-28 07:25 UTC, jaemuYeo commented on OpenMarket/OpenMarket/Model/Type/Product.swift
> +    let vendorName: String?
해당 프로퍼티는 API문서를 보았을때 제외해도 될 것 같네요 :)

2022-10-28 07:25 UTC, jaemuYeo commented on OpenMarket/OpenMarket/Model/Type/Product.swift
> +    let images: [Image]?
코드 중복을 줄이는 것보다는 조금 더 명확한 타입 분리가 이루어졌으면 좋겠어요!

2022-10-28 07:25 UTC, jaemuYeo commented on OpenMarket/OpenMarket/Model/Type/Vendors.swift
> +struct Vendors: Codable {
다시보니 타입명이 복수형인 것보단 명사가 좋겠쥬?

2022-10-31 00:53 UTC, wormsJJG commented on OpenMarket/OpenMarket/Model/Network/NetworkError.swift
> +    case HTTPStatusCodeError
소문자로 수정하겠습니다

2022-10-31 00:53 UTC, wormsJJG commented on OpenMarket/OpenMarket/Model/Network/NetworkError.swift
> +    case UnownURL
invalidURL이 좋겠네요!

2022-10-31 00:54 UTC, wormsJJG commented on OpenMarket/OpenMarket/Model/Network/NetworkManager.swift
> +            }
넵

2022-10-31 00:54 UTC, wormsJJG commented on OpenMarket/OpenMarket/Model/Network/NetworkManager.swift
> +        }
넵

2022-10-31 00:54 UTC, wormsJJG commented on OpenMarket/OpenMarket/Model/Network/Request.swift
> +    case getProductList(pageNo: Int, itemsPerPage: Int)
수정하겠습니다

2022-10-31 00:55 UTC, wormsJJG commented on OpenMarket/OpenMarket/Model/Type/Product.swift
> +struct Product: Codable {
넵!

2022-10-31 00:55 UTC, wormsJJG commented on OpenMarket/OpenMarket/Model/Type/Vendors.swift
> +struct Vendors: Codable {
넵

2022-10-31 01:01 UTC, kr-yeon commented on OpenMarket/OpenMarket/Model/Network/Request.swift
> +    var url: String {
바디 쿼리 파라미터를 나누는것이 현 상황에서 재사용성이 충분히 있다고 생각하지 않습니다.
저러한 기준으로 나누면 코드가 너무 복잡해지고, url을 가져오는 코드에 들어가는 보일러플레이트 코드가 너무 많아진다고 생각됩니다.

2022-11-01 05:43 UTC, jaemuYeo commented on OpenMarket/OpenMarket/Model/Network/Request.swift
> +    var url: String {
코드는 항상 현상황을 보지않고 `앞으로`를 보며 작성해주면 좋아요~
버전 업데이트가 되면서  화면이 추가되고 서버가 갈아엎어지고 그런 상황에서
현재 코드를 사용한다면 일일이 찾아가서 수정해주는 불상사가 발생하지 않을까요?? 😭
[URLComponents](https://developer.apple.com/documentation/foundation/urlcomponents)에 대해 알아보고
적용해봐도 좋을 것같습니다!

2022-11-01 05:47 UTC, jaemuYeo reviewed
Step1 고생많았습니다!!
이번스텝에서는 대략적인 틀을 보며 코멘트 드렸습니다!
다음 스텝에서는 조금 더 설계에 대한 구체적인 모습들을 기대할게요!
스터디 주제에도 올렸던 [블로그](https://ios-development.tistory.com/719)를 참고해보면 좋겠습니다!

스텝2에서 만나요~

2022-11-01 05:47 UTC, jaemuYeo commented on OpenMarket/OpenMarket/Error/Error.swift
> +import Foundation
해당 파일은 추후에 사용되나요?

2022-11-01 05:47 UTC, merged