[STEP1] 도도, 우노
tasty-code/ios-open-market pull request #3
Opened 2022-11-04 05:48 UTC by dddowon

## 구현내용
- `OpenMarketAPI` - 서버 통신 프로토콜 구현
- `OpenMarketURL` - URL 구조 프로토콜 구현
- `NetWorkError` - 통신할 때 발생하는 에러 구현
- `NetWork` - 네트워크 통신 함수 구현
- 매칭할 모델 타입들 구현
- Mock 데이터 유닛 테스트 진행

## 아쉬운 점
- 저희가 POP 방식 말고 두 모델을 한번에 처리할 수 있는 하나의 메서드를 구현하고 싶었는데 이게 마음처럼 구현되지 않은 점
- URL 구조를 나눌 때 `URLComponent` 메서드를 활용하여 쿼리 파라미터를 만들어서 나누고 싶었지만 완성 못한 점

2022-11-08 02:45 UTC, jaemuYeo requested changes
도도우노 스텝1 고생많았습니다!!
오타 때문에 우여곡절이 많았지만 잘 해주었네요 👏👍
POP에 대한 부분도 사실 정답은 없는 것이니
코드를 작성하다가 반복적인 부분이 보일때나 공통된 부분을 간결하게 하고싶을때 (일반화, 추상화)
두분의 입맛대로 구현해보시면 됩니다!!
지금도 충분히 많이 고민하시고 적용해본 티가 나요!! 💯
코멘트 읽어보시고 반영할 부분 수정 후 재요청 주시면 머지진행하겠습니다~!

2022-11-08 02:45 UTC, jaemuYeo commented on OpenMarket/JSONParsingTests/JSONParsingTests.swift
> +    func test_파싱한데이터_pageNo와_1이랑_비교() {
데이터 파싱했을때 pageNo의 번호는 1이다 와 같은 형식으로 네이밍과 테스트를 진행해보면 좋을 것같습니다!

2022-11-08 02:45 UTC, jaemuYeo commented on OpenMarket/JSONParsingTests/JSONParsingTests.swift
> +    func test_파싱_되는지_확인() {
당연히 파싱이 된다는 가정하에 테스트를 진행해야하기때문에 파싱된 데이터를 추출하는 과정을 테스트해보면 좋을 것같아요~

2022-11-08 02:45 UTC, jaemuYeo commented on OpenMarket/JSONParsingTests/JSONParsingTests.swift
> +final class JSONParsingTests: XCTestCase {
Test에 대한 부분이 조금 아쉬워요~
JSON 파싱에 대한 부분을 조금 더 손 본후에 given when then 패턴을 활용해서 조금 더 확실하게 진행해보았으면 좋겠습니다!

2022-11-08 02:45 UTC, jaemuYeo commented on OpenMarket/OpenMarket/Controller/ViewController.swift
> +        network.getDetailPageData { (result: Result<DetailPage, Error>) in
테스트한 코드는 당장 필요한 것이 아니니 지워주세요~~

2022-11-08 02:45 UTC, jaemuYeo commented on OpenMarket/OpenMarket/Error/NetWorkError.swift
> +        case .unknownError:
이런 경우 그냥 unknown으로 해주어도 됩니다!

2022-11-08 02:45 UTC, jaemuYeo commented on OpenMarket/OpenMarket/Error/NetWorkError.swift
> +            return "status코드가 200에서 299사이가 아닙니다."
너무 디테일한 내용보단 요청에 실패했다는 간단한 메시지를 남겨보세요! ☺️

2022-11-08 02:45 UTC, jaemuYeo commented on OpenMarket/OpenMarket/Error/NetWorkError.swift
> +        case .decodingError:
decoding에 대한 에러는 따로 분리해주어도 좋을 것같아요!
JSONParser에 대해서요~

2022-11-08 02:45 UTC, jaemuYeo commented on OpenMarket/OpenMarket/Model/UrlComponents.swift
> +//  UrlComponent.swift
해당 파일은 프로젝트 상에서는 남아있지 않네요!

2022-11-08 02:45 UTC, jaemuYeo commented on OpenMarket/OpenMarket/NetWork/JsonParser.swift
> +class JsonParser {
클래스가 아닌 프로토콜 + 기본구현을 통해 디코딩방식을 조금 더 범용적으로 사용할 수있게 만들면 좋을 것같습니다!
만국박람회때도 해봤던 기억이 있을거예요 :)
제네릭을 활용하여 시도해보세요!

2022-11-08 02:45 UTC, jaemuYeo commented on OpenMarket/OpenMarket/NetWork/JsonParser.swift
> +        let product = try? jsonDecoder.decode(ListPage.self, from: dataAsset.data)
guard let을 통해 디코딩이 실패할때의 에러를 던져주면 좋을 것같습니다!

2022-11-08 02:45 UTC, jaemuYeo commented on OpenMarket/OpenMarket/NetWork/NetWork.swift
> +        let url = host + listPath + queryParameter
지금 같은 형식도 좋습니다 :)
Components는 천천히 익혀보도록 하세요!!
몇번 테스트작성해보면 금방 익힐 수 있을 겁니다 💪

2022-11-08 02:45 UTC, jaemuYeo commented on OpenMarket/OpenMarket/NetWork/NetWork.swift
> +    var host: String {
해당 프로퍼티들을 저장 프로퍼티가 아닌 연산프로퍼티로 선언한 이유가 궁금합니다!

2022-11-08 02:45 UTC, jaemuYeo commented on OpenMarket/OpenMarket/NetWork/NetWork.swift
> +    func getOpenMarketData<T: Decodable>(url: String, completion: @escaping (Result<T, Error>) -> Void ) {
Result 타입 활용 너무 좋습니다 👍👍👍

2022-11-08 02:45 UTC, jaemuYeo commented on OpenMarket/OpenMarket/Protocol/API.swift
> +protocol API {
좋은 POP 형식이네요!! 💯

2022-11-08 02:45 UTC, jaemuYeo commented on OpenMarket/OpenMarket/Protocol/OpenMarketURL.swift
> +protocol OpenMarketURL {
URLComponents를 사용하지 않을 것이라면 지금 형식보다는 static let을 통해 이곳에서 값들을 가지고 있어도 좋을 것같아요~

2022-11-08 04:44 UTC, dddowon commented on OpenMarket/JSONParsingTests/JSONParsingTests.swift
> +    func test_파싱한데이터_pageNo와_1이랑_비교() {
테스트 파일에서도 좀 신경써서 네이밍을 해야하겠네요!

2022-11-08 04:44 UTC, eunho8713 commented on OpenMarket/JSONParsingTests/JSONParsingTests.swift
> +    func test_파싱_되는지_확인() {
넵 반영하겠습니다!

2022-11-08 05:03 UTC, dddowon commented on OpenMarket/JSONParsingTests/JSONParsingTests.swift
> +final class JSONParsingTests: XCTestCase {
넵 활용해보겠습니다!

2022-11-08 05:03 UTC, dddowon commented on OpenMarket/OpenMarket/Error/NetWorkError.swift
> +        case .unknownError:
넵

2022-11-08 05:03 UTC, eunho8713 commented on OpenMarket/OpenMarket/Controller/ViewController.swift
> +        network.getDetailPageData { (result: Result<DetailPage, Error>) in
넵 반영하겠습니다!

2022-11-08 05:04 UTC, eunho8713 commented on OpenMarket/OpenMarket/Error/NetWorkError.swift
> +            return "status코드가 200에서 299사이가 아닙니다."
넵 간단하게 수정해보겠습니다!

2022-11-08 05:07 UTC, dddowon commented on OpenMarket/OpenMarket/Error/NetWorkError.swift
> +        case .decodingError:
넵 JSONParser 에러를 관리하는 파일을 새로 하나 만들었습니다!

2022-11-08 05:09 UTC, eunho8713 commented on OpenMarket/OpenMarket/Model/UrlComponents.swift
> +//  UrlComponent.swift
넵

2022-11-08 05:10 UTC, dddowon commented on OpenMarket/OpenMarket/NetWork/JsonParser.swift
> +        let product = try? jsonDecoder.decode(ListPage.self, from: dataAsset.data)
넵

2022-11-08 05:13 UTC, eunho8713 commented on OpenMarket/OpenMarket/NetWork/JsonParser.swift
> +        let product = try? jsonDecoder.decode(ListPage.self, from: dataAsset.data)
넵 반영해보겠습니다!

2022-11-08 05:14 UTC, dddowon commented on OpenMarket/OpenMarket/NetWork/NetWork.swift
> +    var host: String {
url구조 프로퍼티를 따로 관리하고 싶어서 extension을 활용하여 구현했는데 extension에는 저장 프로퍼티로 선언이 가능하지 않아 연산 프로퍼티로 선언하였습니다!

2022-11-08 06:00 UTC, eunho8713 commented on OpenMarket/OpenMarket/NetWork/NetWork.swift
> +        let url = host + listPath + queryParameter
넵!

2022-11-08 06:00 UTC, eunho8713 commented on OpenMarket/OpenMarket/NetWork/NetWork.swift
> +    func getOpenMarketData<T: Decodable>(url: String, completion: @escaping (Result<T, Error>) -> Void ) {
😎

2022-11-08 06:01 UTC, eunho8713 commented on OpenMarket/OpenMarket/Protocol/API.swift
> +protocol API {
👍👍

2022-11-09 02:08 UTC, dddowon commented on OpenMarket/OpenMarket/NetWork/JsonParser.swift
> +class JsonParser {
넵

2022-11-09 02:09 UTC, dddowon commented on OpenMarket/OpenMarket/Protocol/OpenMarketURL.swift
> +protocol OpenMarketURL {
넵

2022-11-10 02:11 UTC, jaemuYeo reviewed
도도 우노 스텝1 고생많았습니다!!
어려운만큼 중요한 내용인데 잘 학습하고 진행해주었군요 👏
코멘트에 대한 부분은 다음 스텝을 진행하며 반영해보면 좋을 것 같아요~~
POP설계와 타입 설계는 경험치가 쌓일수록 뚝딱 생각이 날 거니까
자주 연습해보고 생각해보면 좋아요 :)
스텝2로 고고!!

2022-11-10 02:11 UTC, jaemuYeo commented on OpenMarket/OpenMarket/Error/JSONParsingError.swift
> +enum JSONParsingError: Error, LocalizedError {
굿 👍

2022-11-10 02:11 UTC, jaemuYeo commented on OpenMarket/OpenMarket/Controller/ViewController.swift
> +        let a = try? jsonParser.getMockData()
테스트 코드가 아직 남아있네요ㅎㅎ

2022-11-10 02:11 UTC, jaemuYeo commented on OpenMarket/OpenMarket/NetWork/JSONParser.swift
> +    var product: Product?
외부에서 접근하지 않아도 된다면 접근제어를 활용해주세요!
Product를 getMockData의 매개변수를 통해 전달하는 방법은 어떤가요??

2022-11-10 02:11 UTC, jaemuYeo commented on OpenMarket/OpenMarket/NetWork/JSONParser.swift
> +        guard let mock = try? mockParsingData(name: fileName, data: product) else { throw NetWorkError.unknownError }
개행의 형태를 참고해주세요~
```swift
 guard let mock = try? mockParsingData(name: fileName, data: product) else {
    throw NetWorkError.unknownError
}
```
아래 return문도 한번의 개행을 주면 조금 더 보기 좋을 것같아요!

2022-11-10 02:11 UTC, jaemuYeo commented on OpenMarket/OpenMarket/NetWork/NetWork.swift
> +        task.resume()
resume위에 중괄호와 한번 개행해주세용~~

2022-11-10 02:11 UTC, jaemuYeo commented on OpenMarket/OpenMarket/Protocol/JSONDecodable.swift
> +    func mockParsingData<T: Decodable>(name: String, data: T) throws -> T? {
반환타입을 옵셔널로 한 이유는 무엇인가요??

2022-11-10 02:11 UTC, jaemuYeo commented on OpenMarket/OpenMarket/Protocol/JSONDecodable.swift
> +        let jsonDecoder = JSONDecoder()
guad let과 상수선언 사이에 간격이 없으니 읽을때 어려움이 있는거 같아요 🤔

2022-11-10 02:12 UTC, merged

2022-11-10 02:57 UTC, eunho8713 commented on OpenMarket/OpenMarket/Error/JSONParsingError.swift
> +enum JSONParsingError: Error, LocalizedError {
😎

2022-11-10 02:57 UTC, dddowon commented on OpenMarket/OpenMarket/Controller/ViewController.swift
> +        let a = try? jsonParser.getMockData()
아 지웠습니다!

2022-11-10 02:57 UTC, eunho8713 commented on OpenMarket/OpenMarket/NetWork/JSONParser.swift
> +    var product: Product?
파라미터 값으로 전달하는 방법이 더 효과적인것 같네요 반영해보겠습니다!

2022-11-10 02:58 UTC, eunho8713 commented on OpenMarket/OpenMarket/NetWork/NetWork.swift
> +        task.resume()
넵

2022-11-10 02:58 UTC, eunho8713 commented on OpenMarket/OpenMarket/Protocol/JSONDecodable.swift
> +        let jsonDecoder = JSONDecoder()
넵 반영하겠습니다!

2022-11-10 02:59 UTC, dddowon commented on OpenMarket/OpenMarket/Protocol/JSONDecodable.swift
> +    func mockParsingData<T: Decodable>(name: String, data: T) throws -> T? {
처음에 옵셔널로 해놨는데 저희가 guard let으로 옵셔널 추출을 해 데이터를 리턴하기에 옵셔널이 아니어도 될거같네요!